repos:
  -repo: local
  hook:
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    types: [python]
    args:
      [
        "-rn",
        "-sn",
        "--rcfile=pylintrc",
        "--load-plugins=pylinst.extensions.docparams"
      ]