repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "--rcfile=.pylintrc",
            "--load-plugins=pylint.extensions.docparams"
          ]